apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: content-application-1
  namespace: argocd
spec:
  project: my-project-1

  source:
    repoURL: https://github.com/berrrrt/argocdconfig.git
    targetRevision: HEAD
    path: testapp
   
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-content-1
