apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project-1
  namespace: argocd
spec:
  description: Example Project one
  sourceRepos:
    - https://github.com/berrrrt/helmconfig.git

  destinations:
    - namespace: demo-content-1
      server: https://kubernetes.default.svc
    - namespace: demo-content-2
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'